### ISSUE TITLE
Add an option to not use mod_rpaf-compatible config?

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/wsgi-mod-rpaf#6]
I'd like to use wsgi-mod-rpaf but I don't have a legacy of using mod-rpaf, so I'd prefer not to use the mod_rpaf-compatible config.

What if we could provide the list of subnets when setting up the middleware? e.g. when constructing my wsgi app:

```python
def app(environ, start_response):
    ...

app = wsgi_mod_rpaf_middleware(
    app,
    # alternatively, it could require already-instantiated ipaddress.IPv4Network objects
    trusted_subnets={'10.0.0.0/8', '192.168.0.0/16'},
)
```

In my case, I'd like to read those IPs out of a JSON file that already exists, which I could do pretty easily with an API like this.

**Comment by asottile** [comment]
Sounds like a good idea to me, offers better flexibility.

Could even improve the interface significantly by making the following breaking change:

```python
app = wsgi_mod_rpaf_middleware(
    app,
    # for apache-based configurations
    trusted_subnets=from_apache_config('/path/to/rpaf.conf'),
)
```

This may also enable someone to do something like

```python

app = wsgi_mod_rpaf_middleware(
    app,
    # for apache-based configurations, using the *new* name for rpaf proxy ips directive
    trusted_subnets=from_apache_config('/path/to/rpaf.conf', directive='RPAF_ProxyIPs '),
)
```

this would enable any input datatype -- the problem would be how much work this might be from yelp's end

**Comment by asottile** [comment]
Ahh dangit, I'm not on this repository either, @tomelm can you hook me up :D

**Comment by tomelm** [comment]
Done!
